// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1NupktKGxqtdh9pZPXY2ChOQPKBOPRH0',
    appId: '1:273325715965:web:ca90773980ce4c38f06994',
    messagingSenderId: '273325715965',
    projectId: 'agro-60b75',
    authDomain: 'agro-60b75.firebaseapp.com',
    storageBucket: 'agro-60b75.firebasestorage.app',
    measurementId: 'G-NT4L1XE11F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRC3xOO6oJBbObSlJbqKL3OOhs-Vn38E',
    appId: '1:273325715965:android:d014eee57beddb2ff06994',
    messagingSenderId: '273325715965',
    projectId: 'agro-60b75',
    storageBucket: 'agro-60b75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMwbhTcI6YYAGqrFu7onLoWM1xsKH8CIA',
    appId: '1:273325715965:ios:9fb8cfe12fa1f65cf06994',
    messagingSenderId: '273325715965',
    projectId: 'agro-60b75',
    storageBucket: 'agro-60b75.firebasestorage.app',
    iosBundleId: 'com.example.agroControlPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMwbhTcI6YYAGqrFu7onLoWM1xsKH8CIA',
    appId: '1:273325715965:ios:9fb8cfe12fa1f65cf06994',
    messagingSenderId: '273325715965',
    projectId: 'agro-60b75',
    storageBucket: 'agro-60b75.firebasestorage.app',
    iosBundleId: 'com.example.agroControlPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1NupktKGxqtdh9pZPXY2ChOQPKBOPRH0',
    appId: '1:273325715965:web:e46752918401572ef06994',
    messagingSenderId: '273325715965',
    projectId: 'agro-60b75',
    authDomain: 'agro-60b75.firebaseapp.com',
    storageBucket: 'agro-60b75.firebasestorage.app',
    measurementId: 'G-2NFBHCV8GG',
  );
}
